name = "alblog"
compatibility_date = "2025-5-12"

[assets]
directory = "./public"
not_found_handling = "404-page"

[build]
command = "hugo -e production"

[var]
HUGO_VERSION = "v0.147.2+extended+withdeploy"
